#!/bin/bash
# Rebuilds the whole site into ./site (docs/ = published pages, src/ = sources). Run from the src directory.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"; cd "$HERE"
WS="${WS:-$HERE/..}"; OUT="${OUT:-$HERE/site}"; REPO="${REPO_URL:-https://github.com/jQrgen/presentations}"
D="$OUT/docs"; rm -rf "$OUT"; mkdir -p "$D/talks/files" "$D/nexa-vs-bitcoin-ethereum" "$OUT/src/brand" "$OUT/src/data"
# Nexa deck: viewers (slides rendered earlier into site-en/site-no), pptx + pdf
PPTX_URL="../Nexa-vs-Bitcoin-Ethereum.pptx" PDF_URL="../Nexa-vs-Bitcoin-Ethereum.pdf" node site.js en >/dev/null
PPTX_URL="../Nexa-vs-Bitcoin-Ethereum-NO.pptx" PDF_URL="../Nexa-vs-Bitcoin-Ethereum-NO.pdf" node site.js no >/dev/null
cp -R site-en "$D/nexa-vs-bitcoin-ethereum/en"; cp -R site-no "$D/nexa-vs-bitcoin-ethereum/no"
rm -f "$D/nexa-vs-bitcoin-ethereum/en/nexa-logo.svg" "$D/nexa-vs-bitcoin-ethereum/no/nexa-logo.svg"
node langpicker.js "$D/nexa-vs-bitcoin-ethereum" "Nexa vs Bitcoin and Ethereum" "Nexa mot Bitcoin og Ethereum" >/dev/null   # index.html: language picker -> en/ or no/
cp "$WS/Nexa-vs-Bitcoin-Ethereum.pptx" "$WS/Nexa-vs-Bitcoin-Ethereum-NO.pptx" "$D/nexa-vs-bitcoin-ethereum/"
cp render/Nexa-vs-Bitcoin-Ethereum.pdf render-no/Nexa-vs-Bitcoin-Ethereum-NO.pdf "$D/nexa-vs-bitcoin-ethereum/"
# Blockchain Game Jam deck: slides/NN.png, .pptx and .pdf live in docs/blockchain-game-jam (rendered from the python-pptx build); the viewer is regenerated
mkdir -p "$D/blockchain-game-jam"; cp -R "$WS/docs/blockchain-game-jam/." "$D/blockchain-game-jam/"
node site-gamejam.js data/blockchain-game-jam-notes.json "$D/blockchain-game-jam" >/dev/null
# Live Tailstorm DAG view (stormtest demo): static page, data comes live from the Nexa core dev publisher
mkdir -p "$D/tailstorm"; cp -R "$WS/docs/tailstorm/." "$D/tailstorm/"
# Nexa team org chart: rendered from data/nexa-team.json (refresh the snapshot with: node orgchart/build-orgchart.js)
node orgchart/build-orgchart.js --render --out "$D" >/dev/null
# old talks as original PDFs
cp talk1/render/deck.pdf "$D/talks/files/patch.pdf"; cp pages/public/patch/cover.png "$D/talks/files/patch-cover.png"
cp oldtalks/tobm-2017.pdf "$D/talks/files/tobm-2017.pdf"; cp oldtalks/tobm-2017-cover.png "$D/talks/files/tobm-2017-cover.png"
cp oldtalks/bitcoin-securities-2018.pdf "$D/talks/files/bitcoin-securities-2018.pdf"; cp oldtalks/bitcoin-securities-2018-cover.png "$D/talks/files/bitcoin-securities-2018-cover.png"
# Exeter 2025 lecture slides and NexScript lab workbook are committed in docs/talks/files
cp "$WS/docs/talks/files/exeter-2025-lecture-slides.pdf" "$WS/docs/talks/files/exeter-2025-lecture-slides-cover.png" "$WS/docs/talks/files/exeter-2025-nexscript-lab-workbook.pdf" "$D/talks/files/"
# pages
node home.js data "$D" "$REPO"
touch "$D/.nojekyll"
# sources
mkdir -p "$OUT/src/orgchart"; cp orgchart/*.js orgchart/*.sh "$OUT/src/orgchart/" 2>/dev/null || true
cp build.js chart.js content-en.js content-no.js site.js site-gamejam.js viewer.js theme.js share.js langpicker.js home.js gl_commit.py package.json build-site.sh "$OUT/src/"
cp brand/*.svg "$OUT/src/brand/"; cp data/*.json "$OUT/src/data/"
cat > "$OUT/.gitlab-ci.yml" <<'YML'
# Mirrors docs/ to GitLab Pages (GitHub Pages serves docs/ directly).
pages:
  stage: deploy
  image: alpine:3.20
  script:
    - mkdir -p public && cp -R docs/. public/
  artifacts:
    paths: [public]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
YML
cat > "$OUT/README.md" <<'MD'
# Presentations, talks, articles and papers

**Live site: https://jqrgen.github.io/presentations/**

Personal site of Jørgen S. Notland: every talk, Medium article and academic paper on one page, grouped by year with the newest first.

- `docs/` is the published site. The `gh-pages` branch holds a copy of `docs/` at its root, which is what GitHub Pages serves; `.gitlab-ci.yml` mirrors it to GitLab Pages as a staging copy.
- `src/data/` holds the content: `talks.json`, `articles.json`, `papers.json`. Edit these and rebuild.
- `docs/nexa-team/` is the Nexa team org chart, generated by `src/orgchart/build-orgchart.js` from the roster snapshot `src/data/nexa-team.json` (refresh and republish with `src/orgchart/publish.sh`).
- `src/` holds the generators: `home.js` (the one-page timeline), `viewer.js` + `site.js` / `site-gamejam.js` (browser viewers for new decks), `build.js` + `chart.js` + `content-*.js` (the Nexa deck as .pptx). Nexa branding is used only inside that deck's slides; the site itself uses the plain theme in `theme.js`.

## Rebuild

```bash
cd src && npm install && ./build-site.sh
```
MD
echo "site: $(find "$OUT" -type f | wc -l) files, $(du -sh "$OUT" | cut -f1)"
